### PR TITLE
Update README with ITA lang

### LINKED ISSUE #8: Update README with ITA lang
Add a link for [README ita](https://github.com/Schrodinger-Hat/community/blob/main/ITA/README.md) on the main README.

We can use [🇮🇹](https://emojipedia.org/flag-italy/) to do it, by simply add this somewhere on README:

```
[🇮🇹](https://github.com/Schrodinger-Hat/community/blob/main/ITA/README.md)
```

It could work.

### PR DESCRIPTION
**Pull request by nicpuppa**
Closes #8

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Review by Wabri — CHANGES_REQUESTED** [review]
Could you add also something to the ita readme to go back?

**Comment by davideimola** [comment]
Sorry, wrong account, yes it would be awesome to add it in the Italian Readme too to go back :+1:

**Comment by nicpuppa** [comment]
@davideimola @Wabri which flag do you suggest to use ? 🇬🇧  or 🇺🇸

**Comment by davideimola** [comment]
Nice question @nicpuppa. Perhaps the flags are not the perfect solution, as different countries can use the same language... it can be not so inclusive I think...

**Comment by davideimola** [comment]
Nice question @nicpuppa. Perhaps the flags are not the perfect solution, as different countries can use the same language... it can be not so inclusive I think...

**Comment by Wabri** [comment]
A simple back arrow emoji? https://emojipedia.org/back-arrow/

**Comment by nicpuppa** [comment]
I don't like the back arrow solution, maybe we can use just the language name. English, Italian ....

**Comment by Wabri** [comment]
Ok for me

**Review by davideimola — APPROVED** [review]
LGTM

**Review by Wabri — APPROVED** [review]

**Pull request merged**
